{
 "title": "KubeVirt / Infrastructure Resources / Top Consumers",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "4h" },
   { "name": "top_consumers", "label": "Number of Top Consumers", "query": "5" },
   {
    "name": "top_cpu_usage_consumers",
    "query": "query_result(topk(${top_consumers}, sum(rate(container_cpu_usage_seconds_total{container=\"compute\",pod=~\"virt-launcher-.*\"}[${interval}])) by (namespace,pod)))"
   },
   {
    "name": "top_memory_swap_traffic_consumers",
    "query": "query_result(topk(${top_consumers}, sum(rate(kubevirt_vmi_memory_swap_traffic_bytes_total[${interval}])) by (namespace, name)))"
   },
   {
    "name": "top_vcpu_wait_consumers",
    "query": "query_result(topk(${top_consumers}, sum(rate(kubevirt_vmi_vcpu_wait_seconds[${interval}])) by (namespace, name)))"
   },
   {
    "name": "top_network_traffic_consumers",
    "query": "query_result(topk(${top_consumers}, sum(rate(kubevirt_vmi_network_traffic_bytes_total[${interval}])) by (namespace, name)))"
   },
   {
    "name": "top_storage_traffic_consumers",
    "query": "query_result(topk(${top_consumers}, sum(rate(kubevirt_vmi_storage_traffic_bytes_total[${interval}])) by (namespace, name)))"
   },
   {
    "name": "top_storage_iops_consumers",
    "query": "query_result(topk(${top_consumers}, sum(rate(kubevirt_vmi_storage_iops_total[${interval}])) by (namespace, name)))"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Memory Swap Traffic Consumers",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(${top_consumers}, sum(rate(kubevirt_vmi_memory_swap_traffic_bytes_total[${interval}])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top vCPU Wait Consumers",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(${top_consumers}, sum(rate(kubevirt_vmi_vcpu_wait_seconds[${interval}])) by (namespace, name))) >0"
    }
   ]
  },
  {
   "title": "Top VM Container CPU Usage Consumers",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(${top_consumers}, sum(rate(container_cpu_usage_seconds_total{container=\"compute\",pod=~\"virt-launcher-.*\"}[${interval}])) by (namespace,pod)))>0"
    }
   ]
  },
  {
   "title": "Top Network Traffic Consumers",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(${top_consumers}, sum(rate(kubevirt_vmi_network_traffic_bytes_total[${interval}])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Storage Traffic Consumers",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(${top_consumers}, sum(rate(kubevirt_vmi_storage_traffic_bytes_total[${interval}])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Storage IOPS Consumers",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(${top_consumers}, sum(rate(kubevirt_vmi_storage_iops_total[${interval}])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Memory Swap Traffic Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_memory_swap_traffic_bytes_total{name=~\"$top_memory_swap_traffic_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM Name: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top vCPU Wait Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_vcpu_wait_seconds{name=~\"$top_vcpu_wait_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM Name: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top VM Container CPU Usage Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$top_cpu_usage_consumers\"}[$__rate_interval])) by (pod, namespace)",
     "legendFormat": "Pod Name: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top Network Traffic Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_network_traffic_bytes_total{name=~\"$top_network_traffic_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM Name: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top Storage Traffic Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_storage_traffic_bytes_total{name=~\"$top_storage_traffic_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM Name: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top Storage IOPS Consumers (over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_storage_iops_total{name=~\"$top_storage_iops_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM Name: {{name}} Namespace: {{namespace}}"
    }
   ]
  }
 ]
}