{
 "title": "KubeVirt / Infrastructure Resources / Top Consumers",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "top_cpu_usage_consumers",
    "query": "query_result(topk(5, avg_over_time(container_cpu_usage_seconds_total{pod=~\"virt-launcher-.*\"}[${__range_s}s]))) "
   },
   {
    "name": "top_memory_swap_traffic_consumers",
    "query": "query_result(topk(5, avg_over_time(kubevirt_vmi_memory_swap_traffic_bytes_total[${__range_s}s])))"
   },
   {
    "name": "top_vcpu_wait_consumers",
    "query": "query_result(topk(5, avg_over_time(kubevirt_vmi_vcpu_wait_seconds[${__range_s}s])))"
   },
   {
    "name": "top_network_traffic_consumers",
    "query": "query_result(topk(5, avg_over_time(kubevirt_vmi_network_traffic_bytes_total[${__range_s}s])))"
   },
   {
    "name": "top_storage_traffic_consumers",
    "query": "query_result(topk(5, avg_over_time(kubevirt_vmi_storage_traffic_bytes_total[${__range_s}s])))"
   },
   {
    "name": "top_storage_iops_consumers",
    "query": "query_result(topk(5, avg_over_time(kubevirt_vmi_storage_iops_total[${__range_s}s])))"
   },
   {
    "name": "top_current_cpu_usage_consumers",
    "query": "query_result(topk(5, container_cpu_usage_seconds_total{pod=~\"virt-launcher-.*\"})) "
   },
   {
    "name": "top_current_memory_swap_traffic_consumers",
    "query": "query_result(topk(5, kubevirt_vmi_memory_swap_traffic_bytes_total))"
   },
   {
    "name": "top_current_vcpu_wait_consumers",
    "query": "query_result(topk(5, kubevirt_vmi_vcpu_wait_seconds))"
   },
   {
    "name": "top_current_network_traffic_consumers",
    "query": "query_result(topk(5, kubevirt_vmi_network_traffic_bytes_total))"
   },
   {
    "name": "top_current_storage_traffic_consumers",
    "query": "query_result(topk(5, kubevirt_vmi_storage_traffic_bytes_total))"
   },
   {
    "name": "top_current_storage_iops_consumers",
    "query": "query_result(topk(5, kubevirt_vmi_storage_iops_total))"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Memory Swap Traffic Consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_memory_swap_traffic_bytes_total{name=~\"$top_memory_swap_traffic_consumers\"}[$__rate_interval])) by (name, namespace)"
    }
   ]
  },
  {
   "title": "Top Memory Swap Traffic Consumers - Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_memory_swap_traffic_bytes_total{name=~\"$top_current_memory_swap_traffic_consumers\"}[$__rate_interval])) by (name, namespace)"
    }
   ]
  },
  { "title": "Top vCPU Wait time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top vCPU Wait Consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_vcpu_wait_seconds{name=~\"$top_vcpu_wait_consumers\"}[$__rate_interval])) by (name, namespace)"
    }
   ]
  },
  {
   "title": "Top vCPU Wait Consumers - Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_vcpu_wait_seconds{name=~\"$top_current_vcpu_wait_consumers\"}[$__rate_interval])) by (name, namespace)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Top VM Container CPU Usage Consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$top_cpu_usage_consumers\"}[$__rate_interval])) by (pod, namespace)",
     "legendFormat": "Pod: {{pod}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top VM Container CPU Usage Consumers - Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$top_current_cpu_usage_consumers\"}[$__rate_interval])) by (pod, namespace)",
     "legendFormat": "Pod: {{pod}} Namespace: {{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Top Network Traffic Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_network_traffic_bytes_total{name=~\"$top_network_traffic_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top Network Traffic Consumers - Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_network_traffic_bytes_total{name=~\"$top_current_network_traffic_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Top Storage Traffic Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_storage_traffic_bytes_total{name=~\"$top_storage_traffic_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top Storage Traffic Consumers - Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_storage_traffic_bytes_total{name=~\"$top_current_storage_traffic_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top Storage IOPS Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_storage_iops_total{name=~\"$top_storage_iops_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM: {{name}} Namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "Top Storage IOPS Consumers - Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kubevirt_vmi_storage_iops_total{name=~\"$top_current_storage_iops_consumers\"}[$__rate_interval])) by (name, namespace)",
     "legendFormat": "VM: {{name}} Namespace: {{namespace}}"
    }
   ]
  }
 ]
}